laravel-project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/', 'DashboardController');
Route::resource('kategori', 'KategoriController');
Route::resource('slider', 'SliderController');
Route::resource('postingan', 'PostinganController');
Route::resource('main', 'MainController');

laravel-project/app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'slider';

    protected $fillable = ['nama_gambar', 'gambar'];
}

laravel-project/app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slider;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slider = Slider::latest()->paginate(10);
        return view('admin.slider.index', compact('slider'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(
            $request,
            [
                'nama_gambar'   => 'required|min:3',
                'gambar'        => 'required|image|mimes:jpg,png,jpeg|max:2048'
            ],
            [
                'nama_gambar.required' => 'Nama Slider minimal 3 huruf',
            ]
        );

        $gambar = $request->gambar;

        $gmbr_slider = time() . $gambar->getClientOriginalName();

        $slider = Slider::create([
            'nama_gambar' => $request->nama_gambar,
            'gambar' => 'public/uploads/slider/' . $gmbr_slider
        ]);

        $gambar->move('public/uploads/slider/', $gmbr_slider);

        return redirect()->route('slider.index')->with('toast_success', 'Slider Berhasil di tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
        return view('admin.slider.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_gambar'   => 'required|min:3'
        ]);

        $slider = Slider::findorfail($id);

        if ($request->has('gambar')) {
            $gmbr_slider = $request->gambar;
            $gambar_slider_baru = time() . $gmbr_slider->getClientOriginalName();
            $gmbr_slider->move('public/uploads/slider/', $gambar_slider_baru);

            $slider_data = [
                'nama_gambar' => $request->nama_gambar,
                'gambar' => 'public/uploads/slider/' . $gambar_slider_baru
            ];
        } else {
            $slider_data = [
                'nama_gambar' => $request->nama_gambar,
            ];
        }

        $slider->update($slider_data);

        return redirect()->route('slider.index')->with('toast_success', 'Slider Berhasil di edit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::findorfail($id);
        $slider->delete();

        return redirect()->back()->with('toast_success', 'Slider Berhasil di hapus!');
    }
}

laravel-project/resources/views/admin/slider/create.blade.php
@extends('backend.konten')

@section('judul', 'Tambah Slider')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('slider.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Nama Slider</label>
                            <input type="text" class="form-control" name="nama_gambar" id="formGroupExampleInput" placeholder="Masukkan Nama Slider">
                            <div class="invalid-feedback">
                                Tambahkan slider.
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlFile1">Tambahkan File Gambar</label>
                            <input type="file" class="form-control-file" name="gambar" id="exampleFormControlFile1">
                        </div>
                        <a href="{{route('slider.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan Slider</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/slider/edit.blade.php
@extends('backend.konten')

@section('judul', 'Edit Slider')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('slider.update', $slider->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                        <div class="form-group">
                            <label for="formGroupExampleInput">Edit Nama Slider</label>
                            <input type="text" class="form-control" value="{{$slider->nama_gambar}}" name="nama_gambar" id="formGroupExampleInput" placeholder="Masukkan Nama Kategori">
                            <div class="invalid-feedback">
                                Tambahkan slider.
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlFile1">Tambahkan File Gambar</label>
                            <input type="file" class="form-control-file" name="gambar" id="exampleFormControlFile1">
                        </div>

                        <div class="form-group">
                            <img src="{{asset($slider->gambar)}}" width="20%" height="30%">
                        </div>
                        <a href="{{route('slider.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan Slider</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/slider/index.blade.php
@extends('backend.konten')

@section('judul', 'Slider')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-2">
            <div class="mb-2 float-lg-left">
            <a href="{{route('slider.create')}}" class="btn btn-primary">Tambah Slider</a>
            </div>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nama Slider</th>
                    <th scope="col">Gambar</th>
                    <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($slider as $item)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td>{{$item -> nama_gambar}}</td>
                            <td>
                                <img src="{{asset( $item->gambar )}}" alt="" style="width:150px;">
                            </td>
                            <td width="15%">
                                <form action="{{route('slider.destroy',$item->id)}}" method="post">
                                @csrf
                                @method('delete')
                                <a href="{{route('slider.edit', $item->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{$slider->links()}}
        </div>
    </div>
</div>

@endsection