laravel-project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/', 'DashboardController');
Route::resource('kategori', 'KategoriController');
Route::resource('slider', 'SliderController');
Route::resource('postingan', 'PostinganController');
Route::resource('main', 'MainController');

laravel-project/app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';

    protected $fillable = ['nama_kategori', 'slug'];
}

laravel-project/app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Kategori;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::latest()->paginate(10);
        return view('admin.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_kategori' => 'required',
        ]);

        Kategori::create([
            'nama_kategori' => $request->nama_kategori,
            'slug'          => Str::slug($request->nama_kategori)
        ]);

        return redirect()->route('kategori.index')->with('toast_success', 'Kategori Berhasil di tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('admin.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_kategori' => 'required',
        ]);

        $kategori_data = [
            'nama_kategori' => $request->nama_kategori,
            'slug' => Str::slug($request->nama_kategori)
        ];

        Kategori::whereId($id)->update($kategori_data);

        return redirect()->route('kategori.index')->with('toast_success', 'Kategori Berhasil di edit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::findorfail($id);

        $kategori->delete();

        return redirect()->route('kategori.index')->with('toast_success', 'Kategori Berhasil di hapus!');
    }
}

laravel-project/resources/views/admin/kategori/create.blade.php
@extends('backend.konten')

@section('judul', 'Tambah Kategori')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('kategori.store')}}" method="POST">
                    @csrf
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Kategori</label>
                            <input type="text" class="form-control" name="nama_kategori" id="formGroupExampleInput" placeholder="Masukkan Nama Kategori">
                        </div>
                        <a href="{{route('kategori.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan Kategori</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/kategori/edit.blade.php
@extends('backend.konten')

@section('judul', 'Edit Kategori')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('kategori.update',$kategori->id)}}" method="POST">
                    @csrf
                    @method('put')
                        <div class="form-group">
                            <label for="formGroupExampleInput">Edit Kategori</label>
                            <input type="text" class="form-control" value="{{$kategori->nama_kategori}}" name="nama_kategori" id="formGroupExampleInput" placeholder="Masukkan Nama Kategori">
                        </div>
                        <a href="{{route('kategori.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan Kategori</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/kategori/index.blade.php
@extends('backend.konten')

@section('judul', 'Kategori')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-2">
            <div class="mb-2 float-lg-left">
            <a href="{{route('kategori.create')}}" class="btn btn-primary">Tambah Kategori</a>
            </div>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nama Kategori</th>
                    <th scope="col">Slug</th>
                    <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($kategori as $item)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td>{{$item -> nama_kategori}}</td>
                            <td>{{$item -> slug}}</td>
                            <td width="15%">
                                
                                <form action="{{route('kategori.destroy',$item->id)}}" method="post">
                                @csrf
                                @method('delete')
                                <a href="{{route('kategori.edit', $item->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
            {{$kategori->links()}}
        </div>
    </div>
</div>

@endsection