laravel-project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/', 'DashboardController');
Route::resource('kategori', 'KategoriController');
Route::resource('slider', 'SliderController');
Route::resource('postingan', 'PostinganController');
Route::resource('main', 'MainController');

laravel-project/app/Postingan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Postingan extends Model
{
    protected $table = 'postingan';

    protected $fillable = ['judul', 'deskripsi', 'kategori_id'];
}

laravel-project/app/Http/Controllers/PostinganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Postingan;
use App\Kategori;

class PostinganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // lakukan join agar menampilkan field slug pada tabel kategori dengan tabel postingan
        $postingan = Postingan::join('kategori', 'kategori.id', '=', 'postingan.kategori_id')
                    ->select('postingan.*', 'kategori.slug')
                    ->latest()->paginate(5);
        return view('admin.postingan.index', compact('postingan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        return view('admin.postingan.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required',
            'deskripsi' => 'required',
            'kategori' => 'required',
        ]);

        Postingan::create([
            'judul' => $request->judul,
            'deskripsi' => $request->deskripsi,
            'kategori_id' => $request->kategori
        ]);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // lakukan join agar menampilkan field nama_kategori pada tabel kategori dengan tabel postingan
        $postingan = Postingan::join('kategori', 'kategori.id', '=', 'postingan.kategori_id')
                    ->select('postingan.*', 'kategori.nama_kategori')
                    ->where('postingan.id', $id)
                    ->first();
        $kategori = Kategori::all();
        return view('admin.postingan.edit', compact('postingan', 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'judul' => 'required',
            'deskripsi' => 'required',
            'kategori' => 'required'
        ]);

        $data_postingan = [
            'judul' => $request->judul,
            'deskripsi' => $request->deskripsi,
            'kategori_id' => $request->kategori
        ];

        Postingan::whereId($id)->update($data_postingan);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di edit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $postingan = Postingan::destroy($id);

        return redirect()->route('postingan.index')->with('toast_success', 'Postingan Berhasil di hapus!');
    }
}

laravel-project/resources/views/admin/postingan/create.blade.php
@extends('backend.konten')

@section('judul', 'Tambah Postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('postingan.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Judul postingan</label>
                            <input type="text" class="form-control" name="judul" id="formGroupExampleInput" placeholder="Masukkan Judul Postingan">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Deskripsi</label>
                            <input type="text" class="form-control" name="deskripsi" id="formGroupExampleInput" placeholder="Masukkan Deskripsi">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Tambahkan Kategori yang Berkaitan</label>
                            <select class="form-control select2 select2-hidden-accessible" name="kategori" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option selected="selected" data-select2-id="">-</option>
                                @foreach ($kategori as $item)
                                    <option data-select2-id="{{$item->id}}" value="{{$item->id}}">{{$item->nama_kategori}}</option>
                                @endforeach
                            </select>
                        </div>
                        <a href="{{route('postingan.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                        <button type="submit" class="btn btn-success btn-sm">Simpan postingan</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/postingan/edit.blade.php
@extends('backend.konten')

@section('judul', 'Edit Postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('postingan.update', $postingan->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="formGroupExampleInput">Edit Judul Postingan</label>
                        <input type="text" class="form-control" value="{{$postingan->judul}}" name="judul" id="formGroupExampleInput" placeholder="Masukkan Judul Postingan">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput">Edit Deskripsi</label>
                        <input type="text" class="form-control" value="{{$postingan->deskripsi}}" name="deskripsi" id="formGroupExampleInput" placeholder="Masukkan Deskripsi">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput">Edit Kategori yang Berkaitan</label>
                        <select class="form-control select2 select2-hidden-accessible" name="kategori" data-select2-id="1" tabindex="-1" aria-hidden="true">
                            <option selected="selected" data-select2-id="{{$postingan->kategori_id}}" value="{{$postingan->kategori_id}}">{{$postingan->nama_kategori}}</option>
                            @foreach ($kategori as $item)
                                <option data-select2-id="{{$item->id}}">{{$item->nama_kategori}}</option>
                            @endforeach
                        </select>
                    </div>
                    <a href="{{route('postingan.index')}}" class="btn btn-primary btn-sm">Kembali</a>
                    <button type="submit" class="btn btn-success btn-sm">Simpan postingan</button>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

@endsection

laravel-project/resources/views/admin/postingan/index.blade.php
@extends('backend.konten')

@section('judul', 'postingan')

@section('isikonten')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-2">
            <div class="mb-2 float-lg-left">
            <a href="{{route('postingan.create')}}" class="btn btn-primary">Tambah postingan</a>
            </div>
            {{-- Kategori yang disimpan hanya bisa disimpan 1 kali --}}
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Judul</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($postingan as $item)
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td>{{$item->judul}}</td>
                            <td>{{$item->deskripsi}}</td>
                            <td><em>#{{$item->slug}}</em></td>
                            <td width="15%">
                                <form action="{{route('postingan.destroy',$item->id)}}" method="post">
                                @csrf
                                @method('delete')
                                <a href="{{route('postingan.edit', $item->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{$postingan->links()}}
        </div>
    </div>
</div>

@endsection